#!/bin/bash

# Path to the encrypted SSH files
enc_dir="$HOME/.dotfiles/ssh/.ssh"
dec_dir="$HOME/.ssh"

# Decrypt the SSH identity files using age and output to the correct location
sops --output "$dec_dir/id_rsa" --age age1mq6usjzvvxvcp7tl03yjdqd0kgjhhvhz48kmg86p43nhx0jc75jssw0kfn --decrypt "$enc_dir/id_rsa.enc"
sops --output "$dec_dir/id_rsa.pub" --age age1mq6usjzvvxvcp7tl03yjdqd0kgjhhvhz48kmg86p43nhx0jc75jssw0kfn --decrypt "$enc_dir/id_rsa.pub.enc"

# Set the correct permissions for the private key
chmod 600 "$dec_dir/id_rsa"
chmod 644 "$dec_dir/id_rsa.pub"
