#!/bin/bash

# Path to the SSH identity files
ssh_dir="$HOME/.dotfiles/ssh/.ssh-test"

# Encrypt the files with age
sops --age age1mq6usjzvvxvcp7tl03yjdqd0kgjhhvhz48kmg86p43nhx0jc75jssw0kfn --encrypt --encrypted-regex '.*' "$HOME/.ssh/id_rsa" > "$ssh_dir/id_rsa.enc"
sops --age age1mq6usjzvvxvcp7tl03yjdqd0kgjhhvhz48kmg86p43nhx0jc75jssw0kfn --encrypt --encrypted-regex '.*' "$HOME/.ssh/id_rsa" > "$ssh_dir/id_rsa.pub.enc"

# Add the encrypted files to Git
git add "$ssh_dir/id_rsa.enc" "$ssh_dir/id_rsa.pub.enc"

