---
system:
    os: linux # Os you are using
    architecture: amd64 # Architecture, we need it here since docker

id_rsa_file: "/home/stefan/.ssh/id_rsa"

local:
    username: stefan
    group: stefan
    userBin: /usr/bin # Where the OS usr bin folder is ( so we can put the binary there )

servers:
    nasIp: "192.168.1.20"