
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/window.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/catppuccin-mocha.toml",
]

