import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/window.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
