---

dependencies: []

galaxy_info:
    role_name: apps
    author: stefangenov
    licence: "license (BSD, MIT)"
    min_ansible_version: 2.9
    description: Installs local apps
    platforms:
        - name: Ubuntu
          versions:
              - all