---
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  loop:
    - repo: ppa:graphics-drivers/ppa
      state: present

- name: Ensure apps are installed
  apt:
    name:
        - curl
        - apt-transport-https
        - chrome-gnome-shell
        - flatpak
        - gnome-software-plugin-flatpak
        - libssl-dev
        - vlc
    state: present
    update_cache: true

- name: KVM Pre-Reqs
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - bridge-utils
      - cpu-checker
      - libvirt-clients
      - libvirt-daemon
      - libgl1-mesa-dri:i386
      - libgl1:i386
      - libc6-i386

- name: Check if Virtualization Capabilities exist
  shell: kvm-ok
  register: kvm_status
  failed_when: '"KVM acceleration can NOT be used" in kvm_status.stdout'
  changed_when: false

- name: Add Flathub
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Check if `/usr/share/keyrings/brave-browser-archive-keyring.gpg` exists
  stat:
    path: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  register: brave_keyring

- name: Download Brave Browser Keyring
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  when: brave_keyring.stat.exists == False

- name: Add Brave Browser Repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
  when: brave_keyring.stat.exists == False

- name: Ensure brave-browser is installed
  apt:
    name:
        - brave-browser
    state: present
    update_cache: true
