---
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  loop:
    - repo: ppa:graphics-drivers/ppa
      state: present
    - repo: ppa:neovim-ppa/unstable
      state: present

- name: Ensure apps are installed
  apt:
    name:
        - apt-transport-https
        - chrome-gnome-shell
        - flatpak
        - gnome-software-plugin-flatpak
        - libssl-dev
    state: present
    update_cache: true

- name: KVM Pre-Reqs
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - bridge-utils
      - cpu-checker
      - libvirt-clients
      - libvirt-daemon

- name: Check if Virtualization Capabilities exist
  shell: kvm-ok
  register: kvm_status
  failed_when: '"KVM acceleration can NOT be used" in kvm_status.stdout'
  changed_when: false

- name: Add Flathub
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
